Blog/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Blog.Models
{
    public class LoginViewModel
    {
        [Required]
        [Display(Name = "Логин")]
        public string UserName { get; set; }

        [Required]
        [UIHint("password")]
        [Display(Name = "Пароль")]
        public string Password { get; set; }

        [Display(Name = "Запомнить?")]
        public bool RememberMe { get; set; }
    }
}

Blog/Models/ViewComponents/SidebarViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Blog.Domain;

namespace Blog.Models.ViewComponents
{
    public class SidebarViewComponent : ViewComponent
    {
        private readonly DataManager dataManager;

        public SidebarViewComponent(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public Task<IViewComponentResult> InvokeAsync()
        {
            return Task.FromResult((IViewComponentResult) View("Default", dataManager.NewsItems.GetSideBarNewsItems()));
        }
    }
}

Blog/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Blog.Domain;

namespace Blog.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        private readonly DataManager dataManager;

        public HomeController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index()
        {
            return View(dataManager.NewsItems.GetNewsItems());
        }
    }
}

Blog/Areas/Admin/Controllers/NewsItemsController.cs
using System;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Blog.Domain;
using Blog.Domain.Entities;
using Blog.Service;

namespace Blog.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class NewsItemsController : Controller
    {
        private readonly DataManager dataManager;
        private readonly IWebHostEnvironment hostingEnvironment;
        public NewsItemsController(DataManager dataManager, IWebHostEnvironment hostingEnvironment)
        {
            this.dataManager = dataManager;
            this.hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Edit(Guid id)
        {
            var entity = id == default ? new NewsItem() : dataManager.NewsItems.GetNewsItemById(id);
            return View(entity);
        }
        [HttpPost]
        public IActionResult Edit(NewsItem model, IFormFile titleImageFile)
        {
            if (ModelState.IsValid)
            {
                if (titleImageFile != null)
                {
                    model.TitleImagePath = titleImageFile.FileName;
                    using (var stream = new FileStream(Path.Combine(hostingEnvironment.WebRootPath, "images/", titleImageFile.FileName), FileMode.Create))
                    {
                        titleImageFile.CopyTo(stream);
                    }
                }
                dataManager.NewsItems.SaveNewsItem(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            dataManager.NewsItems.DeleteNewsItem(id);
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
        }
    }
}

Blog/Areas/Admin/Controllers/TextFieldsController.cs
using Microsoft.AspNetCore.Mvc;
using Blog.Domain;
using Blog.Domain.Entities;
using Blog.Service;

namespace Blog.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TextFieldsController : Controller
    {
        private readonly DataManager dataManager;
        public TextFieldsController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Edit(string codeWord)
        {
            var entity = dataManager.TextFields.GetTextFieldByCodeWord(codeWord);
            return View(entity);
        }

        [HttpPost]
        public IActionResult Edit(TextField model)
        {
            if (ModelState.IsValid)
            {
                dataManager.TextFields.SaveTextField(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }
    }
}

Blog/Controllers/AccountController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Blog.Models;

namespace Blog.Controllers
{
    [Authorize]
    public class AccountController : Controller
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;
        public AccountController(UserManager<IdentityUser> userMgr, SignInManager<IdentityUser> signinMgr)
        {
            userManager = userMgr;
            signInManager = signinMgr;
        }

        [AllowAnonymous]
        public IActionResult Login(string returnUrl)
        {
            ViewBag.returnUrl = returnUrl;
            return View(new LoginViewModel());
        }
        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginViewModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                IdentityUser user = await userManager.FindByNameAsync(model.UserName);
                if (user != null)
                {
                    await signInManager.SignOutAsync();
                    Microsoft.AspNetCore.Identity.SignInResult result = await signInManager.PasswordSignInAsync(user, model.Password, model.RememberMe, false);
                    if (result.Succeeded)
                    {
                        return Redirect(returnUrl ?? "/");
                    }
                }
                ModelState.AddModelError(nameof(LoginViewModel.UserName), "Неверный логин или пароль");
            }
            return View(model);
        }

        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

Blog/Controllers/HomeController.cs
using Blog.Domain;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Blog.Controllers
{
    public class HomeController : Controller
    {
        private readonly DataManager dataManager;

        public HomeController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index()
        {
            return View(dataManager.TextFields.GetTextFieldByCodeWord("PageIndex"));
        }

        public IActionResult Contacts()
        {
            return View(dataManager.TextFields.GetTextFieldByCodeWord("PageContacts"));
        }
    }
}

Blog/Controllers/NewsController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Blog.Domain;
using System.Threading.Tasks;

namespace MyCompany.Controllers
{
    public class NewsController : Controller
    {
        private readonly DataManager dataManager;

        public NewsController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index(Guid id)
        {
            if (id != default)
            {
                return View("Show", dataManager.NewsItems.GetNewsItemById(id));
            }

            ViewBag.TextField = dataManager.TextFields.GetTextFieldByCodeWord("PageNews");
            return View(dataManager.NewsItems.GetNewsItems());


           
        }

       
    }
}

Blog/Areas/Admin/Views/Home/Index.cshtml
@model IQueryable<NewsItem>
@{
    string strTitle = "Панель администратора";
    ViewBag.Title = strTitle;
}

<div>
    <h2>@strTitle</h2>
    <div>
        <h3>Новости</h3>
        <div class="div-box">
            <a asp-area="Admin" asp-controller="NewsItems" asp-action="Edit" asp-route-id="">Добавить новость</a>
        </div>
        @if (Model.Any())
        {
            <div>
                @foreach (NewsItem entity in Model)
                {
                    <div>
                        <a asp-area="Admin" asp-controller="NewsItems" asp-action="Edit" asp-route-id="@entity.Id">редактировать</a>
                        |
                        <form style="display: inline-block;" id="form-@entity.Id" asp-area="Admin" asp-controller="NewsItems" asp-action="Delete" method="post">
                            <input type="hidden" name="id" value="@entity.Id">
                            <a href="#" onclick="document.getElementById('form-@entity.Id').submit();">удалить</a>
                        </form>
                        |
                        <a asp-area="" asp-controller="News" asp-action="Index" asp-route-id="@entity.Id">
                            @($"{entity.Title}")
                        </a>
                    </div>
                }
            </div>
        }
    </div>
    <div class="div-box">
        <h3>Редактировать страницы сайта</h3>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageIndex">Главная</a>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageNews">Новости</a>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageContacts">Контакты</a>
    </div>
    <div class="div-box">
        <form asp-area="" asp-controller="Account" asp-action="Logout" method="post">
            <input type="submit" value="Выйти" />
        </form>
    </div>
</div>

Blog/Areas/Admin/Views/NewsItems/Edit.cshtml
@model NewsItem
@{
    string strTitle = "Редактировать запись";
    ViewBag.Title = strTitle;
}

<script src="~/js/ckeditor/ckeditor.js"></script>

<div>
    <h2>@strTitle</h2>
    <div>
        <form asp-area="Admin" asp-controller="NewsItems" asp-action="Edit" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="DateAdded" />
            <input type="hidden" asp-for="TitleImagePath" />

            <div asp-validation-summary="All"></div>
            <div class="div-box">
                <label asp-for="Title"></label>
                <input asp-for="Title" />
                <span asp-validation-for="Title"></span>
            </div>
            <div class="div-box">
                <label asp-for="Subtitle"></label>
                <input asp-for="Subtitle" />
                <span asp-validation-for="Subtitle"></span>
            </div>
            <div class="div-box">
                <label asp-for="Text"></label>
                <textarea asp-for="Text"></textarea>
                <span asp-validation-for="Text"></span>
            </div>
            <div class="div-box">
                <label asp-for="TitleImagePath"></label>
                <input type="file" name="titleImageFile" id="titleImageFile" />
                <div>
                    <img class="img-block" src="~/images/@Model.TitleImagePath" />
                </div>
            </div>
            <div class="div-box">
                <label asp-for="MetaTitle"></label>
                <input asp-for="MetaTitle" />
                <span asp-validation-for="MetaTitle"></span>
            </div>
          
            <input type="submit" value="Сохранить" />
        </form>
    </div>
</div>



<script>
    window.onload = function() {
        var newCKEdit = CKEDITOR.replace('@Html.IdFor(x=>x.Text)');
        newCKEdit.updateElement();
    }
</script>

Blog/Areas/Admin/Views/TextFields/Edit.cshtml
@model TextField
@{
    string strTitle = "Редактировать страницу";
    ViewBag.Title = strTitle;
}

<script src="~/js/ckeditor/ckeditor.js"></script>

<div>
    <h2>@strTitle</h2>
    <div>
        <form asp-area="Admin" asp-controller="TextFields" asp-action="Edit" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="DateAdded" />
            <input type="hidden" asp-for="CodeWord" />

            <div asp-validation-summary="All"></div>
            <div class="div-box">
                <label asp-for="Title"></label>
                <input asp-for="Title" />
                <span asp-validation-for="Title"></span>
            </div>
            <div class="div-box">
                <label asp-for="Text"></label>
                <textarea asp-for="Text"></textarea>
                <span asp-validation-for="Text"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaTitle"></label>
                <input asp-for="MetaTitle" />
                <span asp-validation-for="MetaTitle"></span>
            </div>
           
            <input type="submit" value="Сохранить" />
        </form>
    </div>
</div>



<script>
    window.onload = function() {
        var newCKEdit = CKEDITOR.replace('@Html.IdFor(x=>x.Text)');
        newCKEdit.updateElement();
    }
</script>

Blog/Views/Home/Contacts.cshtml
@model TextField
@{
    ViewBag.Title = Model.MetaTitle;
    
}

<div>
    @Html.Raw(Model.Text)
</div>

Blog/Views/Home/Index.cshtml
@model TextField
@{
    ViewBag.Title = Model.MetaTitle;
  
}

<div>
    @Html.Raw(Model.Text)
</div>

Blog/Views/News/Index.cshtml
@model IQueryable<NewsItem>
@{
    TextField textField = ViewBag.TextField;

    ViewBag.Title = textField.MetaTitle;
   
}

<div>
    @if (Model.Any())
    {
        <ul class="big-image-list">
            @foreach (NewsItem entity in Model)
            {
                <li>
                    <a asp-area="" asp-controller="News" asp-action="Index" asp-route-id="@entity.Id">
                        <img src="~/images/@entity.TitleImagePath" alt="" class="left" />
                    </a>
                    <h4>@entity.Title</h4>
                    <p>@entity.Subtitle</p>
                </li>
            }
        </ul>
    }
</div>

Blog/Views/News/Show.cshtml
@model NewsItem
@{
    ViewBag.Title = Model.MetaTitle;
  
}

<div>
    <h2>
        @Model.Title
    </h2>
    <h2>
        @Model.Subtitle
    </h2>
    <div>
        <img class="img-block" src="~/images/@Model.TitleImagePath" />
    </div>
</div>
<div>
    @Html.Raw(Model.Text)
</div>

Blog/Views/Services/Index.cshtml
@model IQueryable<NewsItem>
@{
    TextField textField = ViewBag.TextField;

    ViewBag.Title = textField.MetaTitle;
    ViewBag.Description = textField.MetaDescription;
    ViewBag.Keywords = textField.MetaKeywords;
}

<div>
    @if (Model.Any())
    {
        <ul class="big-image-list">
            @foreach (NewsItem entity in Model)
            {
                <li>
                    <a asp-area="" asp-controller="Services" asp-action="Index" asp-route-id="@entity.Id">
                        <img src="~/images/@entity.TitleImagePath" alt="" class="left" />
                    </a>
                    <h4>@entity.Title</h4>
                    <p>@entity.Subtitle</p>
                </li>
            }
        </ul>
    }
</div>

Blog/Views/Shared/Components/Sidebar/Default.cshtml
@model IQueryable<NewsItem>

@if (Model?.Any() == true)
{
    <section>
        <h2>Новости</h2>
        <ul class="small-image-list">
            @foreach (NewsItem entity in Model)
            {
                <li>
                    <a asp-area="" asp-controller="News" asp-action="Index" asp-route-id="@entity.Id">
                        <img src="~/images/@entity.TitleImagePath" alt="" class="left" />
                    </a>
                    <h4>
                        @entity.Title
                    </h4>
                    <p>
                        @entity.Subtitle
                    </p>
                </li>
            }
        </ul>
    </section>
}

Blog/Views/Shared/CssPartial.cshtml
<link rel="stylesheet" href="~/css/main.css" asp-append-version="true" />

Blog/Views/Shared/FooterPartial.cshtml
<div id="footer-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-12">

                <div id="copyright">
                    &copy; @Config.BlogName. All rights reserved.</a>
                </div>

            </div>
        </div>
    </div>
</div>

Blog/Views/Shared/HeaderPartial.cshtml
<div id="header-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-12">

                <header id="header">
                    <h1><a href="/" id="logo">@Config.BlogName</a></h1>
                    <nav id="nav">
                        <a asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        <a asp-area="" asp-controller="News" asp-action="Index" asp-route-id="">Новости</a>
                        <a asp-area="" asp-controller="Home" asp-action="Contacts">Контакты</a>
                    </nav>
                </header>

            </div>
        </div>
    </div>
</div>

Blog/Views/Shared/MetatagsPartial.cshtml
@using Blog.Service
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
@if (ViewBag.Title != null)
{
    <title> @ViewBag.Title</title>
}
else
{
    <title>@Config.BlogName</title>
}

}

Blog/Views/Shared/ScriptsPartial.cshtml
<script src="~/js/scripts.min.js" asp-append-version="true"></script>

Blog/Views/Shared/SidebarPartial.cshtml
<div class="col-4 col-12-medium">

    @(await Component.InvokeAsync<SidebarViewComponent>())

</div>

Blog/Views/Shared/_layout.cshtml
<!DOCTYPE HTML>
<html>
<head>
   @await Html.PartialAsync("MetatagsPartial")
    @await Html.PartialAsync("CssPartial")
</head>
<body>
    <div id="page-wrapper">
        @await Html.PartialAsync("HeaderPartial")
        <div id="main">
            <div class="container">
                <div class="row main-row">
                    <div class="col-8 col-12-medium">
                        @RenderBody()
                    </div>
                    @await Html.PartialAsync("SidebarPartial")
                </div>
               
            </div>
        </div>
        @await Html.PartialAsync("FooterPartial")
    </div>
    @await Html.PartialAsync("ScriptsPartial")
</body>
</html>